# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"-\n\x07Request\x12\x10\n\x08operand1\x18\x01 \x01(\x02\x12\x10\n\x08operand2\x18\x02 \x01(\x02\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x89\x01\n\nCalculator\x12\x1a\n\x03\x41\x64\x64\x12\x08.Request\x1a\t.Response\x12\x1f\n\x08Subtract\x12\x08.Request\x1a\t.Response\x12\x1f\n\x08Multiply\x12\x08.Request\x1a\t.Response\x12\x1d\n\x06\x44ivide\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=65
  _globals['_RESPONSE']._serialized_start=67
  _globals['_RESPONSE']._serialized_end=93
  _globals['_CALCULATOR']._serialized_start=96
  _globals['_CALCULATOR']._serialized_end=233
# @@protoc_insertion_point(module_scope)
